git action v1.1

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -44,6 +44,7 @@ jobs:
         echo "PROJECT_ID=${PROJECT_ID}"
         echo "REGION=${REGION}"
         echo "CLOUD_NAME=${CLOUD_NAME}"
+        echo "DOCKER_IMAGE=${DOCKER_IMAGE}"
 
     - name: Build Docker image
       run: |
@@ -58,6 +59,9 @@ jobs:
 
     - name: Deploy to Google Cloud Run
       run: |
+        if [ -z "${{ env.DOCKER_IMAGE }}" ]; then
+          echo "Error: DOCKER_IMAGE is not set." && exit 1
+        fi
         gcloud run deploy "${{ env.DOCKER_IMAGE }}" \
           --image "${{ env.DOCKER_IMAGE_URI }}" \
           --platform managed \
diff --git a/.github/workflows/deploy-frontend.yml b/.github/workflows/deploy-frontend.yml
--- a/.github/workflows/deploy-frontend.yml
+++ b/.github/workflows/deploy-frontend.yml
@@ -37,6 +37,7 @@ jobs:
         echo "DOCKER_IMAGE_URI=${REGION}-docker.pkg.dev/${PROJECT_ID}/${PROJECT_NAME}/${DOCKER_IMAGE}:${DOCKER_TAG}" >> $GITHUB_ENV
         echo "PROJECT_ID=${PROJECT_ID}"
         echo "REGION=${REGION}"
+        echo "DOCKER_IMAGE=${DOCKER_IMAGE}"
 
     - name: Build Docker image
       run: |
@@ -51,6 +52,9 @@ jobs:
 
     - name: Deploy to Google Cloud Run
       run: |
+        if [ -z "${{ env.DOCKER_IMAGE }}" ]; then
+          echo "Error: DOCKER_IMAGE is not set." && exit 1
+        fi
         gcloud run deploy "${{ env.DOCKER_IMAGE }}" \
           --image "${{ env.DOCKER_IMAGE_URI }}" \
           --platform managed \
